Possibility to sort vendors. Possibility to edit your vendor. Done so…
HabaHaba05/SupportYourLocals pull request #45
Opened 2020-10-20 13:05 UTC by KarolisSm

…me works with mvvm.

2020-10-20 13:43 UTC, HabaHaba05 requested changes
I wrote comments only in AllVendorsVM class, but same changes are needed to be done in other classes also (VendorsVM, MyServicesVM)

2020-10-20 13:43 UTC, HabaHaba05 commented on SuppLocals/SuppLocals/ViewModels/AllVendorsVM.cs
> +    public class AllVendorsVM: BaseViewModel, INotifyPropertyChanged
BaseViewModel already inherits INotifyPropertyChanged, so we don't need to inherit INotifyPropertyChanged.

2020-10-20 13:43 UTC, HabaHaba05 commented on SuppLocals/SuppLocals/ViewModels/AllVendorsVM.cs
> +        public event PropertyChangedEventHandler PropertyChanged;
Don't need it, because we have BaseViewModel.

2020-10-20 13:43 UTC, HabaHaba05 commented on SuppLocals/SuppLocals/ViewModels/AllVendorsVM.cs
> +                }
If we wouldn't have BaseViewModel, Your code would be perfect, but now just write `NotifyPropertyChanged("VendorsList");`

2020-10-26 19:37 UTC, Rangatin commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
> +                    tempVendor.Latitude = Double.Parse(point[0]);
I believe it should be "double" instead of "Double".

2020-10-26 19:37 UTC, Rangatin commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
> +                vendor.Latitude = Double.Parse(point[0]);
Same applies here.

2020-10-26 19:37 UTC, Rangatin commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
>              for(int i = 0; i<VendorList.Count; i++)
Have you tried using foreach instead of for in this instance?

2020-10-26 19:37 UTC, Rangatin commented on SuppLocals/SuppLocals/Views/EditVendor.xaml.cs
>              this.Close();
no need for "this" keyword.

2020-10-26 19:41 UTC, KarolisSm commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
> +                    tempVendor.Latitude = Double.Parse(point[0]);
I will fix it. Thank you!

2020-10-26 19:46 UTC, KarolisSm commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
>              for(int i = 0; i<VendorList.Count; i++)
I didn't think about it.  It is a good idea.

2020-10-26 19:48 UTC, KarolisSm commented on SuppLocals/SuppLocals/Views/EditVendor.xaml.cs
>              this.Close();
I will delete it.

2020-10-26 23:25 UTC, HabaHaba05 commented on SuppLocals/SuppLocals/ViewModels/AllVendorsVM.cs
> +            User user;
I don't have anything against writing like this and actually, I like it more.
But we need to follow coding standards so this should be :
`var user`

But as I can see You use user only in 'using block', so actually i believe you could delete this line and change 47 line to :
`var user = userList.FirstOrDefault(x => x.Username == username);`

2020-10-26 23:25 UTC, HabaHaba05 commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
> +            Vendor vendor = sender as Vendor;
`var vendor = sender as Vendor`

2020-10-26 23:25 UTC, HabaHaba05 commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
> +                db.SaveChanges();
Everything with code is fine.
But if we are deleting the vendor, I think we should delete all reviews about this vendor.

2020-10-26 23:25 UTC, HabaHaba05 commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
> +            Vendor vendor = sender as Vendor;
Again var vendor = sender as Vendor;

2020-10-26 23:25 UTC, HabaHaba05 commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
> +        private async void writeToDatabase(object sender,EventArgs e)
I believe, according to code standards, methods names should Start with the UpperCase letter.

2020-10-26 23:25 UTC, HabaHaba05 commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
> +                vendor.County = point[3];
Wouldn't it work only by assigning tempVendor to the vendor?
I mean :
`vendor = tempVendor;`
Maybe I'm wrong, of course.

2020-10-26 23:25 UTC, HabaHaba05 commented on SuppLocals/SuppLocals/Views/EditVendor.xaml.cs
> +        private void Button_Click(object sender, RoutedEventArgs e)
Button_Click method name is kinda unclear for me. It could be something like ExitBtn_Click or etc.

2020-10-26 23:25 UTC, HabaHaba05 commented on SuppLocals/SuppLocals/ViewModels/VendorsVM.cs
> +            });
For better readability maybe write it in one line, also curly brackets are unnecessary, I think so.

2020-10-26 23:27 UTC, HabaHaba05 approved these changes

2020-10-27 07:18 UTC, StauceLukas commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
> +        private EditVendor editVendor;
I don't think is a problem but it catch my eye that public and private fields mix. It is better that fields would be separated like with empty line or private, private , public order.

2020-10-27 07:24 UTC, StauceLukas commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
> +        }
I am not sure , maybe other could pitch in but ICommand could be change like this :  **public RelayCommand ButtonCommand { get; set; }** and then in constructor : **ButtonCommand= new RelayCommand(o => { EditButtonClick(); }, o => true);** .

2020-10-27 07:30 UTC, StauceLukas commented on SuppLocals/SuppLocals/Views/TabsViews/AddService.xaml.cs
>              if (string.IsNullOrEmpty(address))
Do you think it is better to use IsNullOrEmpty or IsNullOrWhiteSpace ? Because IsNullOrWhiteSpace also include whitespaces.

2020-10-27 07:31 UTC, StauceLukas commented on SuppLocals/SuppLocals/Views/AllVendors.xaml.cs
> +            this.DataContext = new AllVendorsVM(username);
We need this. here?

2020-10-27 07:33 UTC, StauceLukas commented on SuppLocals/SuppLocals/ViewModels/VendorsVM.cs
> +            get { return userList; }
In other viewModel I wrote **get => _test;**. For me it's looks better. How about you?

2020-10-27 07:33 UTC, StauceLukas approved these changes

2020-10-27 07:53 UTC, KarolisSm commented on SuppLocals/SuppLocals/ViewModels/AllVendorsVM.cs
> +            User user;
Oh yes, you are right. I will replace it.

2020-10-27 09:03 UTC, KarolisSm commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
> +                vendor.County = point[3];
I checked, it doesn't work.

2020-10-27 09:05 UTC, KarolisSm commented on SuppLocals/SuppLocals/ViewModels/VendorsVM.cs
> +            });
I agree with you. I will rewrite this.

2020-10-27 09:09 UTC, KarolisSm commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
> +        private EditVendor editVendor;
I fixed it. Thank you.

2020-10-27 09:15 UTC, KarolisSm commented on SuppLocals/SuppLocals/Views/TabsViews/AddService.xaml.cs
>              if (string.IsNullOrEmpty(address))
I believe it can't have whitespaces, because address will be good or it will be empty. Address can't be concluded of whitespaces only.

2020-10-27 09:17 UTC, KarolisSm commented on SuppLocals/SuppLocals/Views/AllVendors.xaml.cs
> +            this.DataContext = new AllVendorsVM(username);
No we don't need it. Thank you for your feedback.

2020-10-27 09:19 UTC, KarolisSm commented on SuppLocals/SuppLocals/ViewModels/VendorsVM.cs
> +            get { return userList; }
In my opinion, my option looks better to me.

2020-10-27 09:23 UTC, KarolisSm commented on SuppLocals/SuppLocals/ViewModels/MyServicesVM.cs
> +        }
It's a good idea, but I don’t think it’s necessary.

2020-10-27 09:27 UTC, HabaHaba05 approved these changes

2020-10-27 09:34 UTC, merged